language: python
python:
  - 3.7

env:
  global:
    - PGPORT=5432

services:
  - postgresql

before_install:
  - sudo apt-get update
  - curl -OsSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
  - python get-poetry.py --preview -y
  - export PATH=$PATH:~/.poetry/bin
  - poetry install
  - poetry update

before_script:
  - psql --version
  - psql -c 'CREATE DATABASE genome_sequencer;' -U postgres

script:
  - poetry run black .
  - poetry run pytest --cov=sequencer tests/
