"""empty message

Revision ID: 05569e8547c6
Revises: 
Create Date: 2021-02-03 19:17:48.447228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05569e8547c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('sequence', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genome')
    # ### end Alembic commands ###
