"""empty message

Revision ID: 06114281aae8
Revises:
Create Date: 2021-03-31 19:52:39.062482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "06114281aae8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("genome", sa.Column("gc_content", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("genome", "gc_content")
    # ### end Alembic commands ###
