"""empty message

Revision ID: a493b155043b
Revises: 05569e8547c6
Create Date: 2021-02-03 20:41:25.853754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a493b155043b"
down_revision = "05569e8547c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("genome", sa.Column("description", sa.String(), nullable=True))
    op.add_column("genome", sa.Column("species", sa.String(), nullable=True))
    op.drop_column("genome", "name")
    op.drop_column("genome", "author")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "genome", sa.Column("author", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "genome", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("genome", "species")
    op.drop_column("genome", "description")
    # ### end Alembic commands ###
